(() => {
  "use strict";
  const D=window.LibraryData,S=D.state,U=window.LibraryUI,$=U.$,esc=U.esc,fmt=U.fmt,cap=U.cap,money=U.money;
  const date=v=>{if(!v)return"—";const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("pt-BR");};
  function openMovie(id){S.selectedMovieId=id;detail();$("#movie-modal").showModal();}
  function detail(){const m=D.getMovie(S.selectedMovieId);if(!m)return;const offers=S.offers.filter(o=>o.movieId===m.id).sort((a,b)=>(a.status==="active"?0:1)-(b.status==="active"?0:1)||D.total(a)-D.total(b)),best=D.bestOffer(m.id),cover=m.coverUrl?`<img src="${esc(m.coverUrl)}" alt="Capa de ${esc(m.title)}">`:`<div class="cover-fallback"><strong>${esc(m.title)}</strong><span>${m.year||""}</span></div>`;$("#movie-detail").innerHTML=`<div class="detail-head"><div class="detail-cover">${cover}</div><div class="detail-title"><p class="eyebrow">${m.status==="owned"?"Na coleção":"Quero comprar"}</p><h2>${esc(m.title)}</h2><p class="detail-sub">${m.year||"Ano não informado"} · ${m.category==="infantil"?"Infantil":"Filmes"}</p><div class="detail-tags">${m.priority?`<span class="badge priority-${m.priority}">Prioridade ${cap(m.priority)}</span>`:""}${(m.tags||[]).map(t=>`<span class="badge">${esc(t)}</span>`).join("")}</div><div class="detail-actions"><button class="secondary-btn" type="button" data-action="edit-movie" data-id="${esc(m.id)}">Editar</button>${m.status==="wanted"?`<button class="primary-btn" type="button" data-action="mark-owned" data-id="${esc(m.id)}">Marcar como comprado</button>`:""}</div>${m.status==="wanted"?`<div class="metrics"><div class="metric"><span>Preço-alvo</span><strong>${fmt(m.targetPrice)}</strong></div><div class="metric"><span>Limite</span><strong>${fmt(m.limitPrice)}</strong></div><div class="metric"><span>Melhor oferta</span><strong>${best?fmt(D.total(best)):"—"}</strong></div></div>`:""}</div></div><section class="detail-section"><div class="detail-section-head"><h3>Ofertas</h3><button class="primary-btn" type="button" data-action="add-offer" data-id="${esc(m.id)}">+ Oferta</button></div><div class="offer-list">${offers.length?offers.map(o=>offerRow(o,best?.id===o.id)).join(""):`<p class="modal-help">Nenhuma oferta cadastrada.</p>`}</div></section>${m.notes?`<section class="detail-section"><h3>Observações</h3><p class="notes">${esc(m.notes)}</p></section>`:""}`;}
  function offerRow(o,best){return `<div class="offer-row ${best?"best":""} ${o.status!=="active"?"offer-status-ended":""}"><div class="offer-store"><strong>${esc(o.store||"Oferta")}</strong><small>${esc(o.seller||"")} ${o.condition?`· ${esc(o.condition)}`:""}</small></div><div class="offer-cell"><span>${fmt(o.price)}</span><small>produto</small></div><div class="offer-cell"><span>${D.num(o.shipping)?fmt(o.shipping):"grátis"}</span><small>frete</small></div><div class="offer-cell offer-total"><span>${fmt(D.total(o))}</span><small>${date(o.checkedAt)}</small></div><div class="row-actions">${o.url?`<a class="mini-btn offer-link" href="${esc(o.url)}" target="_blank" rel="noreferrer" title="Abrir anúncio">↗</a>`:""}<button class="mini-btn" type="button" data-action="end-offer" data-id="${esc(o.id)}" title="Encerrar oferta">✓</button></div></div>`;}
  function movieForm(id=null){const f=$("#movie-form");f.reset();const m=id?D.getMovie(id):null;$("#movie-form-title").textContent=m?"Editar filme":"Adicionar filme";if(m){for(const k of ["id","title","year","status","category","priority","targetPrice","limitPrice","coverUrl","notes"])if(f.elements[k])f.elements[k].value=m[k]||"";f.elements.tags.value=(m.tags||[]).join(", ");}else{f.elements.status.value=S.view;f.elements.category.value=S.category==="all"?"filmes":S.category;}$("#movie-form-modal").showModal();}
  function offerForm(movieId){const f=$("#offer-form");f.reset();f.elements.movieId.value=movieId;f.elements.shipping.value=0;f.elements.fees.value=0;f.elements.checkedAt.value=new Date().toISOString().slice(0,10);f.elements.status.value="active";offerPreview();$("#offer-modal").showModal();}
  function offerPreview(){const f=$("#offer-form");$("#offer-total-preview").textContent=money.format(D.num(f.elements.price.value)+D.num(f.elements.shipping.value)+D.num(f.elements.fees.value));}
  function settings(){const f=$("#settings-form");f.elements.apiUrl.value=S.settings.apiUrl||"";f.elements.apiToken.value=S.settings.apiToken||"";syncStatus(S.settings.apiUrl?"API configurada.":"Modo local.");$("#settings-modal").showModal();}
  function syncStatus(t){$("#sync-status").textContent=t;}
  Object.assign(window.LibraryUI,{openMovie,detail,movieForm,offerForm,offerPreview,settings,syncStatus});
})();
