(() => {
  "use strict";
  const D=window.LibraryData,S=D.state,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}),collator=new Intl.Collator("pt-BR",{sensitivity:"base"}),rank={alta:0,media:1,baixa:2,"":3};
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
  const fmt=v=>D.num(v)>0?money.format(D.num(v)):"—",cap=v=>v?v.charAt(0).toUpperCase()+v.slice(1):"";
  function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2600);}
  function summary(){const owned=S.movies.filter(m=>m.status==="owned").length,wanted=S.movies.filter(m=>m.status==="wanted").length,offers=S.offers.filter(o=>o.status==="active").length;$("#count-owned").textContent=owned;$("#count-wanted").textContent=wanted;$("#count-offers").textContent=offers;const to=$("#tab-count-owned"),tw=$("#tab-count-wanted");if(to)to.textContent=owned;if(tw)tw.textContent=wanted;}
  function filters(){$("#subfilters").innerHTML=[["filmes","Filmes"],["infantil","Infantil"],["all","Todos"]].map(([k,l])=>`<button class="chip ${S.category===k?"active":""}" type="button" data-category="${k}">${l}</button>`).join("");}
  function movies(){const q=$("#search").value.trim().toLocaleLowerCase("pt-BR"),sort=$("#sort").value;let list=S.movies.filter(m=>m.status===S.view);if(S.category!=="all")list=list.filter(m=>m.category===S.category);if(q)list=list.filter(m=>`${m.title} ${m.year||""} ${(m.tags||[]).join(" ")}`.toLocaleLowerCase("pt-BR").includes(q));list.sort((a,b)=>{if(sort==="year-desc")return(b.year||0)-(a.year||0)||collator.compare(a.title,b.title);if(sort==="recent")return String(b.createdAt||"").localeCompare(String(a.createdAt||""));if(sort==="priority")return(rank[a.priority||""]-rank[b.priority||""])||collator.compare(a.title,b.title);if(sort==="best-price")return(D.bestOffer(a.id)?D.total(D.bestOffer(a.id)):Infinity)-(D.bestOffer(b.id)?D.total(D.bestOffer(b.id)):Infinity)||collator.compare(a.title,b.title);return collator.compare(a.title,b.title);});$("#results-line").textContent=`${list.length} ${list.length===1?"filme":"filmes"}`;$("#empty-state").hidden=list.length>0;$("#movie-grid").innerHTML=list.map(card).join("");}
  function card(m){const best=D.bestOffer(m.id),tags=(m.tags||[]).slice(0,2).map(t=>`<span class="badge">${esc(t)}</span>`).join(""),pr=m.status==="wanted"&&m.priority?`<span class="badge priority-${m.priority}">${esc(cap(m.priority))}</span>`:"";const fallback=`<div class="cover-fallback"><strong>${esc(m.title)}</strong><span>${m.year||""}</span></div>`,cover=m.coverUrl?`<img src="${esc(m.coverUrl)}" alt="Capa de ${esc(m.title)}" loading="lazy" onerror="this.remove();this.parentElement.querySelector('.cover-fallback').hidden=false"><div class="cover-fallback" hidden><strong>${esc(m.title)}</strong><span>${m.year||""}</span></div>`:fallback;return `<article class="movie-card" data-movie-id="${esc(m.id)}" tabindex="0"><div class="cover">${cover}<div class="card-flags"><div class="badges">${pr}${tags}</div>${best?`<span class="best-price-pill">${fmt(D.total(best))}</span>`:""}</div></div><div class="movie-meta"><h3>${esc(m.title)}</h3><div class="movie-meta-row"><span>${m.year||""}</span><span class="price-guide">${m.status==="wanted"&&m.targetPrice?`alvo ${fmt(m.targetPrice)}`:""}</span></div></div></article>`;}
  function render(){summary();filters();movies();$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===S.view));}
  window.LibraryUI={...(window.LibraryUI||{}),$,esc,fmt,cap,money,toast,render,movies};
})();
